[MQTTAdapter]
  PORT = "1883"
  TARGET_HOST = "vernemq"
  TARGET_PORT = "1883"
  FORWARDER_TIMEOUT = "30s"
  HEALTH_CHECK = "http://vernemq:8888/health"

[HTTPAdapter]
  PORT = "8080"
  TARGET_HOST = "vernemq"
  TARGET_PORT = "8080"
  TARGET_PATH = "/mqtt"

[General]
  INSTANCE = ""
  JAEGER_URL = "http://jaeger:14268/api/traces"
  INSTANCE_ID = ""
  LOG_LEVEL = "debug"
